FROM python@sha256:540c7d91f98ff6880174c40e99067bf5941eb54d818a7a5e094d188b196a934d AS builder

WORKDIR /manual
COPY requirements-docs.txt .
RUN pip install --no-cache-dir --requirement requirements-docs.txt
COPY mkdocs.yml .
COPY docs ./docs
RUN mkdocs build --strict --site-dir /site

FROM nginx@sha256:db35bfc6b2951e7f8a72db5db120288c127ffaeeb4a6d4b95a26fead017d5913

COPY config/nginx-guide.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /site /usr/share/nginx/html
