server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    add_header Content-Security-Policy "default-src 'self'; style-src 'self'; img-src 'self' data:; object-src 'none'; base-uri 'none'; frame-ancestors 'none'" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header X-Content-Type-Options "nosniff" always;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.md$ {
        types {
            text/plain md;
        }
        try_files $uri =404;
    }
}
